AWSTemplateFormatVersion: 2010-09-09
Parameters:
  HttpIngressPort:
    Type: Number

  ALBName:
    Type: String

Resources:
  WebPageALB:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Type: application
      Name: !Ref ALBName
      Scheme: internet-facing
      SecurityGroups:
        - Fn::ImportValue: ALBSecurityGroup
      Subnets:
        - Fn::ImportValue: PublicSubnetA
        - Fn::ImportValue: PublicSubnetB

  WebPageTargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    DependsOn: WebPageALB
    Properties:
      HealthCheckEnabled: true
      HealthCheckIntervalSeconds: 30
      HealthCheckPath: /
      HealthCheckProtocol: HTTP
      HealthCheckTimeoutSeconds: 5
      HealthyThresholdCount: 5
      Name: WebPageTargetGroup
      Port: !Ref HttpIngressPort
      Protocol: HTTP
      TargetType: ip
      UnhealthyThresholdCount: 2
      VpcId:
        Fn::ImportValue: TaskVPC

  WebPageListener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      DefaultActions:
        - Type: forward
          TargetGroupArn: !Ref WebPageTargetGroup
      LoadBalancerArn: !Ref WebPageALB
      Port: !Ref HttpIngressPort
      Protocol: HTTP


Outputs:
  TargetGroup:
    Description: Reference to target group
    Value: !Ref WebPageTargetGroup
    Export:
      Name: WebPageTargetGroup