AWSTemplateFormatVersion: 2010-09-09

Resources:
  ECSCluster:
    Type: AWS::ECS::Cluster
    Properties:
      ClusterName: ECSCluster
      CapacityProviders:
        - FARGATE
        - FARGATE_SPOT

  WebPageTaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      ExecutionRoleArn:
        Fn::ImportValue: TaskRoleArn
      Family: WebPageTaskDefinition
      ContainerDefinitions:
        - Name: nginx
          MountPoints:
            - SourceVolume: static-volume
              ContainerPath: /usr/share/nginx/html
              ReadOnly: false
          Image: nginx:latest
          PortMappings:
            - ContainerPort: 80
              HostPort: 80
              Protocol: tcp
          Essential: true
      Cpu: 256
      Memory: 512
      NetworkMode: awsvpc
      RequiresCompatibilities:
        - FARGATE
      Volumes:
        - Name: static-volume
          EFSVolumeConfiguration:
            FilesystemId:
              Fn::ImportValue: WebPageEFS
            RootDirectory: /

  WebPageService:
    Type: AWS::ECS::Service
    Properties:
      Cluster: !Ref ECSCluster
      DesiredCount: 2
      LaunchType: FARGATE
      NetworkConfiguration:
        AwsvpcConfiguration:
          AssignPublicIp: ENABLED
          SecurityGroups:
            - Fn::ImportValue: ECSSecurityGroup
          Subnets:
            - Fn::ImportValue: TaskSubnetA
            - Fn::ImportValue: TaskSubnetB
      ServiceName: WebPageService
      LoadBalancers:
        - ContainerName: nginx
          ContainerPort: 80
          TargetGroupArn:
            Fn::ImportValue: WebPageTargetGroup
      TaskDefinition: !Ref WebPageTaskDefinition