AWSTemplateFormatVersion: 2010-09-09
Parameters:
  HttpIngressPort:
    Type: Number

  ECSClusterName:
    Type: String

  ECSClusterCapacityProvider:
    Type: String

  ECSTaskDefinitionFamilyName:
    Type: String

  ECSTaskDefinitionImage:
    Type: String

  CPUAmount:
    Type: Number

  MemoryAmount:
    Type: Number

  ECSServiceTasksCount:
    Type: Number


Resources:
  ECSCluster:
    Type: AWS::ECS::Cluster
    Properties:
      ClusterName: !Ref ECSClusterName
      CapacityProviders:
        - !Ref ECSClusterCapacityProvider

  WebPageTaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      ExecutionRoleArn:
        Fn::ImportValue: TaskRoleArn
      Family: !Ref ECSTaskDefinitionFamilyName
      ContainerDefinitions:
        - Name: !Ref ECSTaskDefinitionImage
          MountPoints:
            - SourceVolume: static-volume
              ContainerPath: /usr/share/nginx/html
              ReadOnly: false
          Image: !Sub "${ECSTaskDefinitionImage}:latest"
          PortMappings:
            - ContainerPort: !Ref HttpIngressPort
              HostPort: !Ref HttpIngressPort
              Protocol: tcp
          Essential: true
      Cpu: !Ref CPUAmount
      Memory: !Ref MemoryAmount
      NetworkMode: awsvpc
      RequiresCompatibilities:
        - !Ref ECSClusterCapacityProvider
      Volumes:
        - Name: static-volume
          EFSVolumeConfiguration:
            FilesystemId:
              Fn::ImportValue: WebPageEFS
            RootDirectory: /

  WebPageService:
    Type: AWS::ECS::Service
    Properties:
      Cluster: !Ref ECSCluster
      DesiredCount: !Ref ECSServiceTasksCount
      LaunchType: !Ref ECSClusterCapacityProvider
      NetworkConfiguration:
        AwsvpcConfiguration:
          AssignPublicIp: DISABLED
          SecurityGroups:
            - Fn::ImportValue: ECSSecurityGroup
          Subnets:
            - Fn::ImportValue: TaskSubnetA
            - Fn::ImportValue: TaskSubnetB
      ServiceName: WebPageService
      LoadBalancers:
        - ContainerName: !Ref ECSTaskDefinitionImage
          ContainerPort: !Ref HttpIngressPort
          TargetGroupArn:
            Fn::ImportValue: WebPageTargetGroup
      TaskDefinition: !Ref WebPageTaskDefinition